---
title: "UC EGC analysis final"
author: "Ryan Brown"
date: "2024-08-21"
output: html_document
---

## Load packages
```{r Load packages}
library(Seurat)
library(cowplot)
library(patchwork)
library(ggplot2)
library(ggthemes)
library(stringr)
library(forcats)
library(clusterProfiler)
library(enrichR)
library(enrichplot)
library(grid)
library(rstatix)
library(readr)
library(tidyr)
library(topGO)
library(org.Hs.eg.db)
library(EnhancedVolcano)
library(SingleCellExperiment)
library(decontX)
library(dplyr)
```


Source data from Kinchen, et. al, 2018: https://doi.org/10.1016/j.cell.2018.08.067

Count files downloaded at: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE95459

Load data and create Seurat object
```{r Load data and create seurat object}
# Load data
# Healthy Controls
HC.counts <- read.table("Expression matrices/GSE114374_Human_HC_expression_matrix.txt")
# UC Patients
UC.counts <- read.table("Expression matrices/GSE114374_Human_UC_expression_matrix.txt")

# Create Seurat object using GEX matrices
HC.Seurat <- CreateSeuratObject(counts = HC.counts, project = 'Healthy_Controls')
UC.Seurat <- CreateSeuratObject(counts = UC.counts, project = 'Ulcerative_Colitis')
# Merge
UC_Seurat.merged <- merge(HC.Seurat, y = UC.Seurat, add.cell.ids = c("HC", "UC"), project = "UC_Seurat.merged")
# Check
UC_Seurat.merged
head(colnames(UC_Seurat.merged))
table(UC_Seurat.merged$orig.ident)
head(UC_Seurat.merged@meta.data)
```

Clustering with integration
```{r}
# Normalize, Find Variable Features, Scale, PCA
UC_Seurat.merged <- NormalizeData(UC_Seurat.merged)
UC_Seurat.merged <- FindVariableFeatures(UC_Seurat.merged)
UC_Seurat.merged <- ScaleData(UC_Seurat.merged)
UC_Seurat.merged <- RunPCA(UC_Seurat.merged)

# Look at UMAP w/out integration
  # Elbow plot
ElbowPlot(UC_Seurat.merged)
  # Find Neighbors
UC_Seurat.merged <- FindNeighbors(UC_Seurat.merged, dims = 1:7, reduction = "pca")
  # Find clusters
UC_Seurat.merged <- FindClusters(UC_Seurat.merged, resolution = 0.3)
  # UMAP
UC_Seurat.merged <- RunUMAP(UC_Seurat.merged, dims = 1:7)
UC_UMAP_grouped_no_integration <- DimPlot(UC_Seurat.merged, reduction = "umap", group.by = "orig.ident")
UC_UMAP_labeled_no_integration <- DimPlot(UC_Seurat.merged, reduction = "umap", label = TRUE)
plot_grid(UC_UMAP_grouped_no_integration  + labs(title = "UC_10x"), UC_UMAP_labeled_no_integration)
# View conditions side by side
DimPlot(UC_Seurat.merged, reduction = "umap", split.by = "orig.ident", label = TRUE) 


# Integrate
UC_Seurat.integrated <- IntegrateLayers(object = UC_Seurat.merged, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca", verbose = F)

# Find Neighbors
UC_Seurat.integrated <- FindNeighbors(UC_Seurat.integrated, reduction = "integrated.cca", dims = 1:8)
# Find Clusters 
UC_Seurat.integrated <- FindClusters(UC_Seurat.integrated, resolution = 0.3, cluster.name = "cca_clusters")

# UMAP
UC_Seurat.integrated <- RunUMAP(UC_Seurat.integrated, reduction = "integrated.cca", dims = 1:8, reduction.name = "umap.cca")
UC_UMAP_grouped <- DimPlot(UC_Seurat.integrated, reduction = "umap.cca", group.by = "orig.ident")
UC_UMAP_labeled <- DimPlot(UC_Seurat.integrated, reduction = "umap.cca", label = TRUE)
plot_grid(UC_UMAP_grouped  + labs(title = "UC_10x"), UC_UMAP_labeled)
# View conditions side by side
DimPlot(UC_Seurat.integrated, reduction = "umap.cca", split.by = "orig.ident", label = TRUE) 
```


Cluster Identification and UMAP labeling
```{r}
## Check cluster IDs using known markers from source publication

# EGCs
VlnPlot(UC_Seurat.integrated, features = c("S100B", "PLP1"))
FeaturePlot(UC_Seurat.integrated, features = c("S100B", "PLP1"), label = T)
  # 5 = EGCs

# Endothelial markers
VlnPlot(UC_Seurat.integrated, features = c("PECAM1"))
  # 2 & 3 = endothelial cells

# Pericytes
VlnPlot(UC_Seurat.integrated, features = c("RGS5"))
  # 8 = Pericytes

# Plasma cells
VlnPlot(UC_Seurat.integrated, features = c("SDC1"))
  # 6 = PCs

# Myofibroblasts
VlnPlot(UC_Seurat.integrated, features = c("ACTA2"))
  # 9 = Myofibroblasts

# Stromal 1
VlnPlot(UC_Seurat.integrated, features = c("ADAMDEC1","CCL8"))
 # 0 = Stromal 1

# Stromal 2
VlnPlot(UC_Seurat.integrated, features = c("SOX6","WNT5A","VSTM2A"))
 # 1 = Stromal 2

# Stromal 3
VlnPlot(UC_Seurat.integrated, features = "EFEMP1")
  # 4 = Stromal 3

# Stromal 4
VlnPlot(UC_Seurat.integrated, features = c("CCL19", "RBP5", "TNFSF13B"))
  #7 = Stromal 4

# Label clusters
UC_Seurat_cluster.ids <- c("Stromal 1", "Stromal 2", "Endothelial Cells 1", "Endothelial Cells 2", "Stromal 3", "Enteric Glial Cells", "Plasma Cells", "Stromal 4", "Pericytes", "Myofibroblasts")
names(UC_Seurat_cluster.ids) <- levels(UC_Seurat.integrated)
UC_Seurat.integrated <- RenameIdents(UC_Seurat.integrated, UC_Seurat_cluster.ids)
options(repr.plot.width = 2, repr.plot.height =3)

# UMAP Plot
UC_UMAP <- DimPlot(UC_Seurat.integrated, reduction = "umap", label = TRUE, label.box = T, label.size = 8, repel = T, cols = c('Stromal 1' = 'chocolate', 'Stromal 2' = 'khaki3', 'Stromal 3' = 'slateblue1', 'Stromal 4' = 'orange', 'Endothelial Cells 1' = 'red', 'Endothelial Cells 2' = 'orchid3', 'Enteric Glial Cells' = 'lawngreen', 'Pericytes' = 'olivedrab', 'Myofibroblasts' = 'lightseagreen', 'Plasma Cells' = 'yellow2')) & theme(axis.line = element_line(size = 1), axis.text = element_text(size = 20), axis.title = element_text(size = 20), axis.ticks = element_line(size = 1), axis.ticks.length = unit(.25, "cm")) & xlab("UMAP 1") & ylab("UMAP 2") & NoLegend()
UC_UMAP
```


Core EGC marker and MHC II expression across clusters
```{r}
# EGC marker plots
DefaultAssay(UC_Seurat.integrated) <- "RNA"
  # Feature plot
UC_EGCmarker_FeaturePlot <- FeaturePlot(UC_Seurat.integrated, features = c("S100B", "PLP1"), label = T) & theme(axis.line = element_line(size = 1), axis.text = element_text(size = 20), axis.title = element_text(size = 20), axis.ticks = element_line(size = 1), axis.ticks.length = unit(.25, "cm"), plot.title = element_text(face = 'bold.italic', size = 20)) & xlab("UMAP 1") & ylab("UMAP 2") & NoLegend()
UC_EGCmarker_FeaturePlot
  # Violin plot
UC_EGCmarker_Vln <- VlnPlot(UC_Seurat.integrated, features = c("S100B", "PLP1"), cols = c('Stromal 1' = 'chocolate', 'Stromal 2' = 'khaki3', 'Stromal 3' = 'slateblue1', 'Stromal 4' = 'orange', 'Endothelial Cells 1' = 'red', 'Endothelial Cells 2' = 'orchid3', 'Enteric Glial Cells' = 'lawngreen', 'Pericytes' = 'olivedrab', 'Myofibroblasts' = 'lightseagreen', 'Plasma Cells' = 'yellow2')) & theme(axis.line = element_line(size = 1), axis.text = element_text(size = 20), title = element_text(size = 20), axis.title.y = element_text(size = 20), axis.title.x = element_blank(), axis.ticks.y = element_line(size = 1), axis.ticks.length.y = unit(.25, "cm"), plot.title = element_text(face = 'bold.italic'))
UC_EGCmarker_Vln


# Fetch S100B/PLP1 expression and cluster # for each cell
UC_EGCmarker_expression <- FetchData(object = UC_Seurat.integrated, vars = c("S100B","PLP1"), layer = "data")
UC_EGCmarker_expression$ClusterID <- FetchData(object = UC_Seurat.integrated, vars = "seurat_clusters")
head(UC_EGCmarker_expression)
  # Sort by cluster
UC_EGCmarker_expression <- arrange(UC_EGCmarker_expression, ClusterID)


  # Count # of cells in EGC cluster that are double positive, single positive, double negative.
EGC_S100B_PLP1_expr <- c((UC_EGCmarker_expression %>% filter(ClusterID == 5) %>% filter(S100B >= 1 & PLP1 >= 1) %>% nrow()), (UC_EGCmarker_expression %>% filter(ClusterID == 5) %>% filter(S100B >= 1 & PLP1 < 1) %>% nrow()), (UC_EGCmarker_expression %>% filter(ClusterID == 5) %>% filter(S100B < 1 & PLP1 >= 1) %>%  nrow()), (UC_EGCmarker_expression %>% filter(ClusterID == 5) %>% filter(S100B < 1 & PLP1 < 1) %>% nrow()))
  # Count # of cells in all other combined clusters that are double positive, single positive, double negative.
Othercluster_S100B_PLP1_expr <- c((UC_EGCmarker_expression %>% filter(ClusterID != 5) %>% filter(S100B >= 1 & PLP1 >= 1) %>% nrow()), (UC_EGCmarker_expression %>% filter(ClusterID != 5) %>% filter(S100B >= 1 & PLP1 < 1) %>% nrow()), (UC_EGCmarker_expression %>% filter(ClusterID != 5) %>% filter(S100B < 1 & PLP1 >= 1) %>%  nrow()), (UC_EGCmarker_expression %>% filter(ClusterID != 5) %>% filter(S100B < 1 & PLP1 < 1) %>% nrow()))

# Create vector w/ cluster ID names
Cluster <- c(rep("EGC cluster", 4), rep("Other clusters", 4))
# Create vector w/ Expression names
Expression <- rep(c("S100B+ PLP1+", "S100B+ PLP1-", "S100b- PLP1+", "S100B- PLP1-"), 2)
# Create vector w/ Cell counts determined above
CellCount <- c(EGC_S100B_PLP1_expr, Othercluster_S100B_PLP1_expr)
# Combine into dataframe
UC_EGCmarker_expression_grouped <- data.frame(Cluster, Expression, CellCount)

# Count total # of cells per group
p <-  UC_EGCmarker_expression_grouped %>% 
  group_by(Cluster) %>% 
  tally(CellCount)
# Create vector w/ # of cells/group
Clustersums <- c(rep(p$n[1], 4), rep(p$n[2],4))
# Add to dataframe
UC_EGCmarker_expression_grouped$Clustersums <- Clustersums

UC_EGCmarker_expression_grouped <- UC_EGCmarker_expression_grouped %>%  
  mutate(percent = (CellCount/Clustersums) *100)

UC_EGCmarker_barplots <- ggplot(UC_EGCmarker_expression_grouped, aes(fill = Cluster, x = Cluster, y = percent)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c("lawngreen", "lemonchiffon4")) +
  geom_text(aes(label = signif(percent, 3)), vjust = -0.5) +
  labs(title = "Ulcerative Colitis Core EGC marker expression", y = "Percent of cluster", x = "Cluster") +
  scale_y_continuous(limits = c(0,110), expand = c(0,0)) +
  scale_x_discrete() +
  facet_wrap(~factor(Expression, c("S100B+ PLP1+", "S100B+ PLP1-", "S100b- PLP1+", "S100B- PLP1-")), scales = 'free') & 
  theme_clean() +
  theme(axis.line = element_line(size = .5), axis.text = element_text(size = 10), title = element_text(size = 20), axis.title.y = element_text(size = 15), axis.title.x = element_blank(), axis.ticks.y = element_line(size = .5), axis.ticks.length.y = unit(.25, "cm"), plot.title = element_text(face = 'bold.italic', size = 20, hjust = .5), strip.text = element_text(size = 14, face = 'bold.italic')) + NoLegend()
UC_EGCmarker_barplots


## Plot MHC II expression across celltypes
# Group similar clusters
UC_Seurat_cluster.ids_grouped <- c("Stromal Cells", "Stromal Cells", "Endothelial Cells", "Endothelial Cells", "Stromal Cells", "Enteric Glial Cells", "Plasma Cells", "Stromal Cells", "Pericytes", "Myofibroblasts")
names(UC_Seurat_cluster.ids_grouped) <- levels(UC_Seurat.integrated)
UC_Seurat.integrated_grouped <- RenameIdents(UC_Seurat.integrated, UC_Seurat_cluster.ids_grouped)
# MHC II plots
  #FeaturePlot
UC_MHCII_FeaturePlot <- FeaturePlot(UC_Seurat.integrated_grouped, features = "HLA-DRB1", label = T, split.by = "orig.ident") & theme(axis.line = element_line(size = 1), axis.text = element_text(size = 20), axis.title = element_text(size = 20), axis.ticks = element_line(size = 1), axis.ticks.length = unit(.25, "cm"), plot.title = element_text(face = 'bold', size = 20)) & xlab("UMAP 1") & ylab("UMAP 2") & NoLegend()
UC_MHCII_FeaturePlot
  # Violin plot
MHCIIgenes <- c("HLA-DMA","HLA-DMB","HLA-DOA","HLA-DPA1","HLA-DPB1","HLA-DQA1","HLA-DQA1","HLA-DQB1","HLA-DRA","HLA-DRB1","HLA-DRB5")
UC_MHCII_Vln <- VlnPlot(UC_Seurat.integrated_grouped, features = MHCIIgenes, split.by = "orig.ident", cols = c("#232D4B", "#E57200"), stack = T, flip = T) & theme(axis.line = element_line(size = 1), axis.text.x = element_text(size = 15), axis.text.y.left = element_text(size = 12), strip.text.y.right = element_text(size = 20, face = 'bold.italic'), title = element_text(size = 20), axis.title.y = element_text(size = 20), axis.title.x = element_blank(), axis.ticks.y = element_line(size = 1), axis.ticks.length.y = unit(.25, "cm"), plot.title = element_text(face = 'bold.italic')) & NoLegend()
UC_MHCII_Vln

```

EGC Subclustering
```{r}
# Subset EGCs by cluster and PLP1,S100B expression > 1
DefaultAssay(UC_Seurat.integrated) 
UC_EGCs = subset(UC_Seurat.integrated, idents = "Enteric Glial Cells")
UC_EGCs = subset(UC_EGCs, PLP1 >= 1 & S100B >= 1)
  # Check cell # /sample
  table(UC_EGCs$orig.ident)
  
JoinLayers(UC_EGCs)  
  
# Normalize, Find Variable Features, Scale, PCA
UC_EGCs <- NormalizeData(UC_EGCs)
UC_EGCs <- FindVariableFeatures(UC_EGC)
all.genes <- rownames(UC_EGCs)
UC_EGCs <- ScaleData(UC_EGCs, features = all.genes)
UC_EGCs <- RunPCA(UC_EGCs)

## Subclustering 
# Look at UMAP w/out integration
  # Elbow plot
ElbowPlot(UC_EGCs)
  # Find Neighbors
UC_EGCs <- FindNeighbors(UC_EGCs, dims = 1:6, reduction = "pca")
  # Find clusters
UC_EGCs <- FindClusters(UC_EGCs, resolution = 0.5)
  # UMAP
UC_EGCs <- RunUMAP(UC_EGCs, dims = 1:8)
UC_EGCs_UMAP_grouped_no_integration <- DimPlot(UC_EGCs, reduction = "umap", group.by = "orig.ident")
UC_EGCs_labeled_no_integration <- DimPlot(UC_EGCs, reduction = "umap", label = TRUE)
plot_grid(UC_EGCs_UMAP_grouped_no_integration  + labs(title = "UC_EGCs"), UC_EGCs_labeled_no_integration)
# View conditions side by side
DimPlot(UC_EGCs, reduction = "umap", split.by = "orig.ident", label = TRUE) 


# Integrate
UC_EGCs.integrated <- IntegrateLayers(object = UC_EGCs, method = CCAIntegration, orig.reduction = "pca", new.reduction = "integrated.cca", verbose = F)

# Find Neighbors
UC_EGCs.integrated <- FindNeighbors(UC_EGCs.integrated, reduction = "integrated.cca", dims = 1:8)
# Find Clusters 
UC_EGCs.integrated <- FindClusters(UC_EGCs.integrated, resolution = 0.5, cluster.name = "cca_clusters")

# UMAP
UC_EGCs.integrated <- RunUMAP(UC_EGCs.integrated, reduction = "integrated.cca", dims = 1:8, reduction.name = "umap.cca")
UC_EGCs_UMAP_grouped <- DimPlot(UC_EGCs.integrated, reduction = "umap.cca", group.by = "orig.ident")
UC_EGCs_UMAP_labeled <- DimPlot(UC_EGCs.integrated, reduction = "umap.cca", label = TRUE)
plot_grid(UC_EGCs_UMAP_grouped  + labs(title = "UC_10x_EGCs"), UC_EGCs_UMAP_labeled)
# View conditions side by side
DimPlot(UC_EGCs.integrated, reduction = "umap.cca", split.by = "orig.ident", label = TRUE) 

  
# EGC marker violin plot
Idents(UC_EGCs) <- "orig.ident"
EGC_Vln <- VlnPlot(UC_EGCs, features = c("S100B", "PLP1"), split.by = "orig.ident", cols = c("#232D4B", "#E57200"), layer = "scale.data") & theme(axis.line = element_line(size = 1), axis.text = element_text(size = 20), title = element_text(size = 20), axis.title.y = element_text(size = 20), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.y = element_line(size = 1), axis.ticks.length.y = unit(.25, "cm"), axis.ticks.x = element_blank(), plot.title = element_text(face = 'bold.italic'))
EGC_Vln
```


Differential Expression and Gene Ontology
```{r}
## DE between conditions in all EGC clusters

# Set RNA default assay, idents to orig.ident
DefaultAssay(UC_EGCs.integrated) <- "RNA"
Idents(UC_EGCs.integrated) <- "orig.ident"
# Join layers
UC_EGCs.integrated <-JoinLayers(UC_EGCs.integrated)
# DE testing using findmarkers
UCvsHC_DE <- FindMarkers(UC_EGCs.integrated, ident.1 = "Ulcerative_Colitis", ident.2 = "Healthy_Controls")
UCvsHC_DE
# Add column for gene symbol
UCvsHC_DE$genesymbol <- rownames(UCvsHC_DE)
# Add column for entrez ID
UCvsHC_DE$entrezID <- mapIds(org.Hs.eg.db, keys = UCvsHC_DE$genes, column = "ENTREZID", keytype = "SYMBOL")
# Drop rows that don't have mapped entrez gene id (mostly mitochondrial_)
UCvsHC_DE <- UCvsHC_DE %>% drop_na()


# Volcano plot
UC_EGCs_DE_HvUC_Volcano <- EnhancedVolcano(UCvsHC_DE, lab = rownames(UCvsHC_DE), x = 'avg_log2FC', y = 'p_val_adj', FCcutoff = 1, labFace = "bold.italic", labSize = 5, legendLabSize = 20, axisLabSize = 20, raster = T, drawConnectors = T, title = NULL, subtitle = NULL, caption = NULL, gridlines.major = F, gridlines.minor = F) & theme(axis.line = element_line(size = 1), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), axis.ticks = element_line(size = 1), axis.ticks.length = unit(.25, "cm"), legend.position = 'top')
UC_EGCs_DE_HvUC_Volcano


## Gene Ontology w/ EnrichGO 
# Subset positively DE genes by avg_log2_FC >1 & p_val_adj <.05 and remove NAs
UC_upregulated <- filter(UCvsHC_DE, avg_log2FC > 1 & p_val_adj < 0.05)
# Check
UC_upregulated

# enrichGO
UC_upregulated_enrichGO <- enrichGO(gene = UC_upregulated$entrezID,
                            OrgDb = org.Hs.eg.db,
                            ont = "BP",
                            pAdjustMethod = "BH",
                            pvalueCutoff = 0.01,
                            qvalueCutoff = 0.05,
                            readable = T)
UC_upregulated_enrichGO
head(UC_upregulated_enrichGO)

# Filter to GO level 4
UC_upregulated_enrichGO <- gofilter(UC_upregulated_enrichGO, level = 4)
# Simplify repetitice GO terms
UC_upregulated_enrichGO <- simplify(UC_upregulated_enrichGO, cutoff =0.7, by ="p.adjust", select_fun=min)


# Bar plot
barplot(UC_upregulated_enrichGO, showCategory = 10)

mutate(UC_upregulated_enrichGO, qscore = -log(p.adjust, base = 10)) %>% 
  barplot(x="qscore", showCategory = 10) 


# Dot plot
UC_upregulated_enrichGO_dotplot <- dotplot(UC_upregulated_enrichGO, showCategory = 5)
    UC_upregulated_enrichGO_dotplot <- UC_upregulated_enrichGO_dotplot & theme(rect = element_rect(linewidth = 1, color = 'black'), axis.line = element_line(size = 1), axis.text.y = element_text(size = 14), title = element_text(size = 20), axis.title.y = element_text(size = 20), axis.title.x = element_text(size = 20), axis.text.x = element_text(size = 20), axis.ticks.y = element_line(size = 1), axis.ticks.length.y = unit(.25, "cm"), legend.text = element_text(size = 14)) 
UC_upregulated_enrichGO_dotplot


## Heatmap of DE genes involved in Antigen Processing/Presentation
#DE genes in KEGG AGPP pathway
AGPP_KEGG_genes <- read.csv("AGPP_genes.csv")
AGPP_KEGG_vector <- AGPP_KEGG_genes$Gene
Idents(UC_EGCs.integrated) <- "orig.ident"
UC_EGCs_AGPP_KEGG <- subset(UC_EGCs.integrated, features = AGPP_KEGG_vector)
UC_EGCs_AGPP_KEGG <- ScaleData(UC_EGCs_AGPP_KEGG)

DefaultAssay(UC_EGCs_AGPP_KEGG) <- "RNA"

AGPP_KEGG_Markers <- FindMarkers(UC_EGCs_AGPP_KEGG, ident.1 = "Healthy_Controls", ident.2 = "Ulcerative_Colitis")
AGPP_KEGG_Markers
AGPP_KEGG_Markers <- subset(AGPP_KEGG_Markers, AGPP_KEGG_Markers$p_val_adj < .05)
AGPP_KEGG_Markers
AGPP_KEGG_Markers$gene <- rownames(AGPP_KEGG_Markers)
AGPP_KEGG_DE_genes <- AGPP_KEGG_Markers$gene
AGPP_KEGG_DE_genes <- sort(AGPP_KEGG_DE_genes)
AGPP_KEGG_DE_gene_index <- c(1,2,2,2,1,1,1,2,2,2,2,2,2,2,2,2,2,2,1,1,3,3,3,3,3,3,1,1,1,1,1)
AGPP_KEGG_DE_genes <- AGPP_KEGG_DE_genes[order(AGPP_KEGG_DE_gene_index)]

DefaultAssay(UC_EGCs.integrated) <- "RNA"
UC_EGCs.genes <- rownames(UC_EGCs.integrated)
UC_EGCs.integrated <- ScaleData(UC_EGCs.integrated, features = UC_EGCs.genes)

UC_EGC_AGPP_Heatmap <- DoHeatmap(UC_EGCs.integrated, features = AGPP_KEGG_DE_genes, group.by = "orig.ident", label = F, group.colors = c("#232D4B", "#E57200")) + theme(axis.text.y = element_text(face = "bold.italic", size = 20), legend.text = element_text(size = 20), legend.title = element_text(size = 20)) + guides(color = "none")
UC_EGC_AGPP_Heatmap
```

## Repeat DE,GO w/ Subclutering of S100B+,PLP1- EGCs
```{r}
# Subset EGCs by cluster and PLP1,S100B expression > 1
DefaultAssay(UC_Seurat.integrated) 
UC_PLPneg_EGCs = subset(UC_Seurat.integrated, idents = "Enteric Glial Cells")
  # Check cell # /sample
  table(UC_PLPneg_EGCs$orig.ident)
UC_PLPneg_EGCs = subset(UC_PLPneg_EGCs, S100B >= 1 & PLP1 < 1)
  # Check cell # /sample
  table(UC_PLPneg_EGCs$orig.ident)
  
# EGC marker violin plot
Idents(UC_PLPneg_EGCs) <- "orig.ident"
PLPneg_EGC_Vln <- VlnPlot(UC_PLPneg_EGCs, features = c("S100B", "PLP1"), split.by = "orig.ident", cols = c("#232D4B", "#E57200")) & theme(axis.line = element_line(size = 1), axis.text = element_text(size = 20), title = element_text(size = 20), axis.title.y = element_text(size = 20), axis.title.x = element_blank(), axis.text.x = element_blank(), axis.ticks.y = element_line(size = 1), axis.ticks.length.y = unit(.25, "cm"), axis.ticks.x = element_blank(), plot.title = element_text(face = 'bold.italic'))
PLPneg_EGC_Vln

##Differential Expression testing
## DE between conditions in all EGC clusters
# Set RNA default assay, idents to orig.ident
DefaultAssay(UC_PLPneg_EGCs) <- "RNA"
Idents(UC_PLPneg_EGCs) <- "orig.ident"
# Join layers
UC_PLPneg_EGCs <-JoinLayers(UC_PLPneg_EGCs)
# DE testing using findmarkers
PLPneg_UCvsHC_DE <- FindMarkers(UC_PLPneg_EGCs, ident.1 = "Ulcerative_Colitis", ident.2 = "Healthy_Controls")
PLPneg_UCvsHC_DE
# Add column for gene symbol
PLPneg_UCvsHC_DE$genesymbol <- rownames(PLPneg_UCvsHC_DE)
# Add column for entrez ID
PLPneg_UCvsHC_DE$entrezID <- mapIds(org.Hs.eg.db, keys = PLPneg_UCvsHC_DE$genes, column = "ENTREZID", keytype = "SYMBOL")
# Drop rows that don't have mapped entrez gene id (mostly mitochondrial_)
PLPneg_UCvsHC_DE <- PLPneg_UCvsHC_DE %>% drop_na()


# Volcano plot
PLPneg_UC_EGCs_DE_HvUC_Volcano <- EnhancedVolcano(PLPneg_UCvsHC_DE, lab = rownames(PLPneg_UCvsHC_DE), x = 'avg_log2FC', y = 'p_val_adj', pCutoff = .05, FCcutoff = 1, labFace = "bold.italic", labSize = 5, legendLabSize = 20, axisLabSize = 20, raster = T, drawConnectors = T, title = NULL, subtitle = NULL, caption = NULL, gridlines.major = F, gridlines.minor = F) & theme(axis.line = element_line(size = 1), axis.text.x = element_text(size = 20), axis.text.y = element_text(size = 20), axis.ticks = element_line(size = 1), axis.ticks.length = unit(.25, "cm"), legend.position = 'top')
PLPneg_UC_EGCs_DE_HvUC_Volcano


## Gene Ontology w/ EnrichGO 
# Subset positively DE genes by avg_log2_FC >1 & p_val_adj <.05 and remove NAs
PLPneg_UC_upregulated <- filter(PLPneg_UCvsHC_DE, avg_log2FC > 1 & p_val_adj < 0.05)
# Check
PLPneg_UC_upregulated

# enrichGO
PLPneg_UC_upregulated_enrichGO <- enrichGO(gene = PLPneg_UC_upregulated$entrezID,
                            OrgDb = org.Hs.eg.db,
                            ont = "BP",
                            pAdjustMethod = "BH",
                            pvalueCutoff = 0.01,
                            qvalueCutoff = 0.05,
                            readable = T)
PLPneg_UC_upregulated_enrichGO
head(PLPneg_UC_upregulated_enrichGO)

# Filter to GO level 4
PLPneg_UC_upregulated_enrichGO <- gofilter(PLPneg_UC_upregulated_enrichGO, level = 4)
# Simplify repetitice GO terms
PLPneg_UC_upregulated_enrichGO <- simplify(PLPneg_UC_upregulated_enrichGO, cutoff =0.7, by ="p.adjust", select_fun=min)


# Bar plot
barplot(PLPneg_UC_upregulated_enrichGO, showCategory = 10)

mutate(PLPneg_UC_upregulated_enrichGO, qscore = -log(p.adjust, base = 10)) %>% 
  barplot(x="qscore", showCategory = 10) 


# Dot plot
PLPneg_UC_upregulated_enrichGO_dotplot <- dotplot(PLPneg_UC_upregulated_enrichGO, showCategory = 5)
    PLPneg_UC_upregulated_enrichGO_dotplot <- PLPneg_UC_upregulated_enrichGO_dotplot & theme(rect = element_rect(linewidth = 1, color = 'black'), axis.line = element_line(size = 1), axis.text.y = element_text(size = 14), title = element_text(size = 20), axis.title.y = element_text(size = 20), axis.title.x = element_text(size = 20), axis.text.x = element_text(size = 20), axis.ticks.y = element_line(size = 1), axis.ticks.length.y = unit(.25, "cm"), legend.text = element_text(size = 14)) 
PLPneg_UC_upregulated_enrichGO_dotplot


## Heatmap of DE genes involved in Antigen Processing/Presentation
#DE genes in KEGG AGPP pathway
Idents(UC_PLPneg_EGCs) <- "orig.ident"
PLPneg_EGCs_AGPP_KEGG <- subset(UC_PLPneg_EGCs, features = AGPP_KEGG_vector)
PLPneg_EGCs_AGPP_KEGG <- ScaleData(PLPneg_EGCs_AGPP_KEGG)

DefaultAssay(PLPneg_EGCs_AGPP_KEGG) <- "RNA"

PLPneg_AGPP_KEGG_Markers <- FindMarkers(PLPneg_EGCs_AGPP_KEGG, ident.1 = "Healthy_Controls", ident.2 = "Ulcerative_Colitis")
PLPneg_AGPP_KEGG_Markers
PLPneg_AGPP_KEGG_Markers <- subset(PLPneg_AGPP_KEGG_Markers, PLPneg_AGPP_KEGG_Markers$p_val_adj < .05)
PLPneg_AGPP_KEGG_Markers
PLPneg_AGPP_KEGG_Markers$gene <- rownames(PLPneg_AGPP_KEGG_Markers)
PLPneg_AGPP_KEGG_DE_genes <- PLPneg_AGPP_KEGG_Markers$gene
PLPneg_AGPP_KEGG_DE_genes <- sort(PLPneg_AGPP_KEGG_DE_genes)
PLPneg_AGPP_KEGG_DE_genes
PLPnegAGPP_KEGG_DE_gene_index <- c(2,1,1,1,2,2,2,2,2,2,2,2,2,1)
PLPneg_AGPP_KEGG_DE_genes <- PLPneg_AGPP_KEGG_DE_genes[order(PLPnegAGPP_KEGG_DE_gene_index)]
PLPneg_AGPP_KEGG_DE_genes

DefaultAssay(UC_PLPneg_EGCs) <- "RNA"
PLPneg_UC_EGCs.genes <- rownames(UC_PLPneg_EGCs)
UC_PLPneg_EGCs <- ScaleData(UC_PLPneg_EGCs, features = PLPneg_UC_EGCs.genes)

PLPneg_UC_EGC_AGPP_Heatmap <- DoHeatmap(UC_PLPneg_EGCs, features = PLPneg_AGPP_KEGG_DE_genes, group.by = "orig.ident", label = F, group.colors = c("#232D4B", "#E57200")) + theme(axis.text.y = element_text(face = "bold.italic", size = 20), legend.text = element_text(size = 20), legend.title = element_text(size = 20)) + guides(color = "none")
PLPneg_UC_EGC_AGPP_Heatmap
```
